baseurl         = "https://aaronjfarnham.github.io"
theme           = "hugo-webslides-master"
languageCode    = "en-us"
title           = "A Hugo theme for creating Webslides.js presentations"

[params]
  author = "RCJacH"
  homepage = "RCJacH.github.io"

[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[blackfriday]
extensionsmask = ["autoHeaderIds"]

[markup]
defaultMarkdownHandler = "blackfriday"
